services:
  myfin-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PW
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PW
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8183:80

volumes:
  mysql_data: